In [2]:
import numpy as np

np.random.rand(5)

array([0.33735352, 0.48418788, 0.48450501, 0.56758113, 0.78369154])

In [13]:
w = np.random.rand(2, 4)
w

array([[0.58138851, 0.4329878 , 0.65160486, 0.59165465],
       [0.65247605, 0.56614194, 0.04654197, 0.89608481]])

In [14]:
w += 1e-2 * np.random.rand(*w.shape)
w

array([[0.58478081, 0.4364838 , 0.6547381 , 0.59874963],
       [0.65772235, 0.57084602, 0.05416047, 0.89770845]])